### ISSUE TITLE
i18n routes

### ISSUE THREAD

**Issue by solidevolution** [chrisvfritz/prerender-spa-plugin#12]
Hey,

is there a solution for i18n routes?

Example:

```
/en/about
/de/über
```

I am worried about the fact that we have to name the files with special characters ...

**Comment by chrisvfritz** [comment]
For umlauts specifically, I usually see two strategies: 

- Cheat. 🙂  For example, studiVZ just uses `/about_us` instead of `über` and `/Unis` instead of `Universitäten`.
- Use the multi-character alternative. For example, `bundesregierung.de` expands the `ä` in `Gebärden` to `ae` to form `Gebaerden`. This is what I usually do.

**Comment by solidevolution** [comment]
Ok then, can you shortly explain me a best practise for i18n with routes, components and prerendering please? I'm a bit confuse atm ;)

**Comment by chrisvfritz** [comment]
There's not a single set of best practices that I know of. Different libraries and organizations often choose to do it differently. If you're using Vue.js, I recommend checking out [vue-i18n](https://kazupon.github.io/vue-i18n/).
