### ISSUE TITLE
Hello, how should this dynamic route be configured??

### ISSUE THREAD

**Issue by hello-guoguo** [chrisvfritz/prerender-spa-plugin#149]
### This directory is also a dynamic routing: /myArtical/: id/, the name of the file is uncertain
```
--myArtical
   --0001.html
   --0002.html
        .
        .
        .
```
## A sincere invitation

**Comment by jnrdt** [comment]
Hi,

You have to implement some logic before populating the array representing the routes to prerender.

A solution can be to store somewhere tha date of the last build that prerendered pages. And at each build, prerender only pages modified since last build.

You may also look at server side rendering

**Comment by hello-guoguo** [comment]
Thx.
Maybe, what I need is the server side rendering, not the prerender.
