### ISSUE TITLE
v3 feedback

### ISSUE THREAD

**Issue by codeofsumit** [chrisvfritz/prerender-spa-plugin#156]
I tried the alpha today.

Here's what problems I encountered:
- node 8 is not sufficient. I upgraded to the latest to make it work (because of the spread operator).
- the `dist` folder is being searched in the `build` folder. Path should be `../dist` instead of `dist` in the docs to fix it
- chrome can't fetch anything:
![image](https://user-images.githubusercontent.com/2399810/36632261-c74f87ca-1984-11e8-84e9-d0a7279844b1.png)

I was not able to resolve the last issue. Any advice?

**Comment by codeofsumit** [comment]
Also `inject: 'head'` causes the app to not mount anymore (`div#app` stays empty`). Setting it back to `true` makes the app mount again.

**Comment by Tribex** [comment]
Noted, I'll take a look at each of those tomorrow. Thanks for the feedback!

**Comment by Tribex** [comment]
@codeofsumit Should be fixed now in `alpha.1`

- Removed Object rest/spread operator usage. Seems to be working fine on Node 8 LTS for me now.
- Fixed and documented the undocumented `skipThirdPartyRequests` option for the puppeteer renderer that was accidentally on by default. (It was causing the Chrome loading error you had.)
- I believe `inject: 'head'` should no longer be necessary, so I've now removed it from the docs. Good catch!

As for changing the `dist` path in the docs, It's currently set that way because it assumes a `webpack.config.js` in the root project directory, in accordance with Vue's `webpack-simple` template. I personally think that it's easier to understand that way, but if you disagree, feel free to make a point against it and I'll consider adjusting the file layout.

**Comment by codeofsumit** [comment]
Hey @Tribex, thanks a ton.

Regarding the docs of the `dist` folder. No worries, It was just something I noticed when trying it on the vue-cli webpack/pwa template.

I've tried out `alpha.1`: I rendered only my main route `/` for now but it's already the first version where there is actually all content inside of the built index.html 🎉 

What I don't get yet, is when does the static page give control to vue to take over? Because if I serve the `dist` folder with an http server, the main route stays empty until it's regularly loaded by vue.
If I open the built `index.html` without a web server, all css & images are missing but the content is there.

Is there anything else I need to do? Actually, I'm not even sure what the finished output has to look like? I thought it's my page, with all content, css and html included in one html file ready to be served to customers and search engines. But I may have misunderstood?

**Comment by Tribex** [comment]
@codeofsumit The easiest way to test and see if it works is to load the page with JavaScript disabled after prerendering and see if your content is still there.

The finished output should only be your document HTML & content (and styles injected from JavaScript.) Nothing else. Images, CSS, and such are not inlined (yet, we may add something like this in the future.) and will still be loaded from their normal locations. 

If your page isn't working with JavaScript disabled, make sure you're not triggering the render too early with `renderAfter*`.

If that still doesn't work, then there's probably a bug somewhere on my end. 

As for when the static page tells Vue to take over... Technically it doesn't. At the moment Vue will just replace all the prerendered DOM when it loads. (If you add the `data-server-rendered="true"` attribute to your Vue mount point during prerendering, it should hydrate the DOM instead of replacing it.)

**Comment by codeofsumit** [comment]
ok in that case: it works 🎉 
![image](https://user-images.githubusercontent.com/2399810/36675918-92ae1522-1b0a-11e8-8ae5-ecd3784a1c73.png)

Content is loaded from contentful. No CSS. No Images.

**Comment by Tribex** [comment]
Hooray! I still feel like the CSS should be there as well, but it really depends on your setup you'd need to delay the prerendering until after any page modifying scripts run.

I'm going to go ahead and close this for now. Have fun!
