### ISSUE TITLE
[help wanted] Prevent browser from loading generated static HTML before Vuejs content

### ISSUE THREAD

**Issue by francoislevesque** [chrisvfritz/prerender-spa-plugin#17]
**Problem**
When my browser is loading for the first time the website, the static HTML pages are shown until the "real" vuejs content appears. This breaks the smoothness of the page, which is very important for this particular project. You can see an example here: [http://draft.witify.io/fr/projects/](http://draft.witify.io/fr/projects/
)

**Question**
Is there a way to "hide" the static content for all vuejs compatible browsers and directly show the vuejs content?

**Possible solutions?**
* Using nginx to redirect all url to index.html doesn't seem to work.

**Comment by chrisvfritz** [comment]
I simply wouldn't prerender in your case. Vue's browser support is good enough (over 99%) according to caniuse.com's stats, so that any users with browsers that don't support Vue will already be accustomed to vast swaths of the Internet being broken for them. If you really do want to accommodate those users however, I'd either use modernizr or possibly just a [`<noscript>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) (for those with JS disabled) to show alternative HTML.

Or you could rework your site so that it doesn't use JS to calculate layout or control animations if that's the case. Then the pre-rendered result would already be perfect.

**Comment by francoislevesque** [comment]
Ok I see, thanks for the fast response by the way!
My main concern is actually SEO. 
I'll try to use CSS instead of JS for layout as you proposed, and maybe take a look at SSR for future projects.

**Comment by chrisvfritz** [comment]
Happy to help. These problems actually wouldn't be solved by SSR though, so I can save you some time in that direction. 🙂
