### ISSUE TITLE
Why Does A '/' Appear On End Of Route?

### ISSUE THREAD

**Issue by gbmhunter** [chrisvfritz/prerender-spa-plugin#191]
If I specify a route as such:
```
routes: ['/tool/pid-tuner']
```
then when I navigate to `/tool/pid-tuner`, the URL in the browser quickly changes to `/tool/pid-tuner/`. I also notice that this plugin has created a static HTML page at `dist/static/tool/pid-tuner/index.html`, when I expected it to create the file at `dist/static/tool/pid-tuner.html`.

**Comment by Tribex** [comment]
@gbmhunter This is intentional, as we're trying to achieve 1:1 relationships between prerendered routes and client-rendered routes. If we render to `dist/static/tool/pid-tuner.html`, then not all web servers will serve `pid-tuner.html` for the route `dist/static/tool/pid-tuner`. However, if we use `dist/static/tool/pid-tuner/index.html`, most web servers will recognize this and serve `index.html` from the `pid-tuner` directory.

**Comment by gbmhunter** [comment]
O.k., sounds like good reasoning. 

However, I did have a look at changing it using `postProcess()`, but it doesn't seem like I have the ability to do so. If I print the `renderedRoute` object that gets passed to the `postProcess()` function, I see:

```
renderedRoute =
{ originalRoute: '/tool/pid-tuner',
  route: '/tool/pid-tuner',
  html: '<!DOCTYPE html><html><head>...
}
```

Note here how there is no forward slash at the end, so no ability to remove it. Looks like it is applied somewhere later in the process? I am using `prerender-spa-plugin v3.1.0` (currently the latest release). Also worth nothing that these three properties in the `renderedRoute` object are significantly different to what is mentioned in the latest version of the README.

**Comment by Tribex** [comment]
@gbmhunter Right, the outputPath property doesn't exist on the renderedRoute object until you create it, and should be the absolute path to wherever you want to write the file.
