### ISSUE TITLE
'Flash' on rendered page when Vue takes over

### ISSUE THREAD

**Issue by assembledadam** [chrisvfritz/prerender-spa-plugin#193]
Hello - I have two routes that are pre-rendered on build using the plugin (Using v3.1.0 with Vue 2.5.13)

Same issue as reported in #131 and #156: "When I load a prerendered page I first see the prerendered page, then the page becomes white again before being hydrated by vue."

I've recorded a demonstration here: https://youtu.be/pOPl00bcEn4

In Issue #156 @Tribex says: "As for when the static page tells Vue to take over... Technically it doesn't. At the moment Vue will just replace all the prerendered DOM when it loads. (If you add the data-server-rendered="true" attribute to your Vue mount point during prerendering, it should hydrate the DOM instead of replacing it.)" . 

I have tried this, but it doesn't appear to change anything:
```html
<div id="app" data-server-rendered="true"></div>
```
My config is as follows:
```node
new PrerenderSpaPlugin({
      // Path to compiled app
      staticDir: path.join(__dirname, '../dist'),
      // List of endpoints you wish to prerender
      routes: [ '/' ],
      // Workaround for async
      renderer: new Renderer({
        renderAfterDocumentEvent: 'render-event'
      }),
      headless: true
    })
```
Any idea why data-server-rendered="true" does not appear to work? Thanks!

**Comment by Tribex** [comment]
@assembledadam I'm not sure what might be the issue here. When are you inserting `data-server-rendered="true"`? Manually afterwards?

**Comment by assembledadam** [comment]
I manually put this into the index.html source template (so before pre-rendering). Just assumed that's where it should go - I can't find any documentation on the feature?

Thanks

**Comment by Tribex** [comment]
@assembledadam See here: https://ssr.vuejs.org/en/hydration.html

**Comment by assembledadam** [comment]
Ok - from here it doesn't say that it needs to be inserted at all, just that you can see it once the page is rendered. Am I supposed to place it in the template before render to get this behaviour? Thanks

**Comment by assembledadam** [comment]
We may have crossed wires... I am not using SSR. My setup: I have VueJS, a customised vuejs specific webpack config, and have also added the prerender-spa-plugin to pre-render a couple of pages for SEO.

My issue is stated in the original post - the DOM appears to be replaced which is causing flashing.

**Comment by Tribex** [comment]
Right, sorry, I'm not being clear. If you're using SSR, the `data-server-rendered` attribute is added automatically. If you're prerendering, you have to add it yourself, which you said you already did.

Regardless, do you think you'd be able to replicate the issue with an example? I'm not making any progress.

**Comment by assembledadam** [comment]
No problem.

I put a test case together and I'm getting similar behaviour (the DOM is totally replaced), but I can't see the visible 'flash' - but then the HTML/styling is totally different, so could be that. Am looking into it further, but will be a few days as I've got other stuff to get done in the mean time. Will report back soon.

**Comment by Tribex** [comment]
Understood. Perhaps there's something I've missed regarding Vue's hydration logic, as adding the attribute to the main app mount point should prevent the DOM replacement. I'll take a closer look.

**Comment by epistemery** [comment]
@assembledadam I have a similar issue. Were you able to resolve it?

**Comment by totomobile43** [comment]
Hi all, I have been working towards solving this issue and have [provided an answer on stackoverflow ](https://stackoverflow.com/questions/51154224/vue-pre-render-spa-root-overwrites-template-file/51218261) which may be helpful, however, it was only part of the solution to fix the flashing:

This SO answer ensures that your production website has the following behaviour:
Landing page ("/" of your site) -> Goes to a pre-rendered dist/index.html
Non-Pre-rendered routes (e.g. /user/5) -> Goes to /dist/app.html (just the plain template).

The other part of the solution is to 'pre-render' your data directly into the html. This ensures that when Vue takes over the page, the store is populated and thus no [] Blank data is loaded causing a flash. The solution is described [here](https://github.com/chrisvfritz/prerender-spa-plugin/issues/145).

I have implemented this by first writing the relevant data into a script variable:
`var script = document.createElement("script");
script.innerHTML = "var prefetchedProducts = " + JSON.stringify(data) + ";";
document.head.appendChild(script);`

And then loading this pre-stored data if it exists:
` if(window.prefetchedProducts){
        context.commit('setProducts', window.prefetchedProducts);
      }`

If you read the Vue SSR documentation, this is not so different from what the server would do, but instead it would write it directly into the [store](https://ssr.vuejs.org/guide/data.html#server-data-fetching).

Finally, because Vue Hydration fails silently in production mode, you must debug it in development or you will not know if you have hydration fails. You can do this by launching a [local server](https://stackoverflow.com/questions/47034452/how-to-run-production-site-after-build-vue-cli) to serve the /dist folder after it has been rendered.

It turned out that I had many issues with my content not lining up, and you will see errors in the console which tell you that Vue failed to hydrate. These issues may be tricky to solve, for example, I ran the [W3 Validator](https://validator.w3.org/) to slowly weed out any major errors like unclosed tags.

I hope these tips get people on the right track, and I will in the meantime work on posting my app as an example in case people need a reference.

**Comment by adrianolobo** [comment]
I solved that issue using this function in the config object

```
     postProcess(context) {
       context.html.replace('id="app"', 'id="app" data-server-rendered="true"')
     },
```

**Comment by joshgeller** [comment]
Does anybody know if React supports something similar to `data-server-rendered="true"`?

**Comment by Tribex** [comment]
Not that I'm aware of.

**Comment by WhiteBookmark** [comment]
I am having the same issue but none of the above solutions worked for me.

What my component does is, fetches some data using axios from an API, and displays it. Now prerendering actually works and in production it does display prerendered data, but then Vue.js overwrites that component and fetches fresh data from same API then displays to user.

Problem here is that there is a delay approximately 500ms due to API response. And because of that, empty component is shown (no prerendered data and no new data) for 500ms. This we can call a flash.

**Comment by dimavolo** [comment]
I am having the same problem as well and none of the above worked for me.

**Comment by Haiwar** [comment]
> 我也有同样的问题，以上都不对我有用。

me too...

**Comment by Haiwar** [comment]
When I enter the page details, the homepage appears and flashes for a few milliseconds...

bug img：
![1](https://user-images.githubusercontent.com/35055270/111408396-37c7ce80-8710-11eb-9da7-1cf0cd36966d.gif)
