### ISSUE TITLE
indexPath is ignored

### ISSUE THREAD

**Issue by pavelstudeny** [chrisvfritz/prerender-spa-plugin#264]
Grepping the whole repository, README.md is the only place containing `indexPath`.  The code contains just
```
const outputFile = path.join(outputDir, 'index.html')
```

Something like
```
this._options.indexPath || 'index.html'
```
could help.

**Comment by Tribex** [comment]
@pavelstudeny `indexPath` is used by [prerenderer](https://github.com/Tribex/prerenderer) to define the source HTML file. It is not used for output, as `folder/index.html` is always used so that paths like `/some/nested/path/` will map to `/some/nested/path/index.html` in the same way as the SPA's internal router.

**Comment by pavelstudeny** [comment]
ok, if index.html is purposely the only possible output, i'm closing this issue
