### ISSUE TITLE
{"statusCode":404,"error":"Not Found"}

### ISSUE THREAD

**Issue by treforcoster** [chrisvfritz/prerender-spa-plugin#45]
Hi there.

I'm using vue.js for a wordpress theme and I'm trying to get this pre-render plugin to work.
I've followed the instructions for set up and the plugin is creating the static files the content of the files is as follows:

{"statusCode":404,"error":"Not Found"} 

If i set the path of the to the theme directory or the worpdress root I still get the same response.

Can anyone help at all?

**Comment by dkimot** [comment]
I have the same issue. Do you get an error message that says "tmpDir() is deprecated, use tmpdir() instead."?

**Comment by ICELI** [comment]
I have the same issue. After i changed the dist path like this
```js
new PrerenderSpaPlugin(
      Path.join(__dirname, '../dist'),
      [ '/' ]
    )
```
It's working! 

Make sure your `webpack.config.js` file relative to the dist directory~

**Comment by ICELI** [comment]
I have the same issue. After i changed the dist path like this
```js
new PrerenderSpaPlugin(
      Path.join(__dirname, '../dist'),
      [ '/' ]
    )
```
It's working!
Make sure your webpack.config.js file relative to the dist directory~

**Comment by jnrdt** [comment]
Hi,

Firstly, `tmpDir() is deprecated, use tmpdir()` is just a warning displayed by one of the dependency.

Secondly, in a more general way, If you have a 404, it's because the full path doesn't lead to your page. There can be two reasons : 
 - the relative path may be wrong (small probability)
 - like @ICELI noticed, the base path may be wrong : be aware of the fact that the script doesn't stand at the root of your project

I will do a pull request that provide a test of the existence of the base path provided.

**Comment by drewlustro** [comment]
@treforcoster - has this been resolved for you? If not, could you please provide detailed instructions on repro?

**Comment by drewlustro** [comment]
HI @treforcoster - check the latest [example for vue2](https://github.com/chrisvfritz/prerender-spa-plugin/tree/master/examples/vue2-webpack-router) in the repo. It should guide you to the right configuration to avoid this error.
