### ISSUE TITLE
How to get working with dynamic menus and multilingual sites

### ISSUE THREAD

**Issue by aaronjpitts** [chrisvfritz/prerender-spa-plugin#46]
Hi,

Is it possible to get your plugin working with small parts of dynamic content still? For example, our homepage is fully static with the exception of the navigation menu, where depending on whether the user is logged in or not, it alters the menu. If the user is not logged in it will show 'Sign Up' and 'Register' links whereas if the user is logged in, it will show a 'Dashboard' link. Is this possible with your plugin? Also, for multilingual sites, how can we get it to pre-render for each page in each language? For example our site papayapods.com is in English and fr.papayapods.com is in French, the language is set at load time depending if there is a language subdomain used (or not for English).

Many thanks

**Comment by jnrdt** [comment]
Hi,

The prerendered page is static and can contain only one version per route. And, since the prerendering is done in non connected context, your navigation menu will show 'Sign Up' and 'Register'. This is probably already the default state of your page, so the prerendering is almost useless in this case.

As for the language, it is the same : if there is one entry point, there is one prerendered page. You can choose wich one you want by default and it will be saved in the generated html, keeping in mind that the prerendering context will not know any of your production hostnames.

At least, your page beeing mostly static, you probably don't need prerendering. But, since you want multiple versions to be calculated as fast as possible for a single entry point, server side rendering, wich is not covered by this module, is probably what you really need.

Hoping it will help

**Comment by drewlustro** [comment]
Agreed 👍
