### ISSUE TITLE
ajax asynchronous data？

### ISSUE THREAD

**Issue by chenweihan** [chrisvfritz/prerender-spa-plugin#48]
If the ajax asynchronous data loading, whether into the static HTML, how to use?

In vue:
            setTimeout(function() {
                //return some date into dom
            }, 2000);

compilation is complete, the content will be generated in the static html.
          
when npm run build ,the setTimeout is OK, but ajax return is not generated in the static html.  
when npm run dev, the ajax is OK.
I think whe the compile, ajax url is not correct request in prerender-spa-plugin.

who can give me some help?

**Comment by jnrdt** [comment]
Hi,

The prerendering will basically load all code "in the flow" that includes synchronous instructions, promises, async/await but not asynchronism handled by callbacks.

You can promisify your async call like so : 

```
let delay = ms => new Promise(r => setTimeout(r, ms));
delay(2000).then(() => {
     //return some date into dom
})
```
If not, you will have to use advanced configuration like explained in the README such as : 

waiting for your call to be finished, say 2500ms on your exemple : 
```
captureAfterTime: 2500
```

or, since you said that your callback insert DOM, you can wait for an element to be present in the DOM
```
setTimeout(function() {
     document.body.id = "content"
}, 2000);
```
and use this option in the module configuration : 
```
 captureAfterElementExists: '#content'
```

Finally, you can fire an event when your callback is done like so : 
```
setTimeout(function() {
     document.dispatchEvent(new Event('custom-post-render-event'))
}, 2000);
```
and use this option in the module configuration : 
```
captureAfterDocumentEvent: 'custom-post-render-event'
```


I hope it will help

**Comment by chenweihan** [comment]
Hi  @jnrdt:
    Thank you for your advice

     I want to say is the asynchronous loading is normal, but ajax callback is  can't,  the ajax use the agent.

    eg: 
  proxyTable: {
            '/api': {
                target: 'http://rest.xxxxxx.com/',
                changeOrigin: true,
                pathRewrite: {
                    '^/api/': ''
                }
            }

        }

**Comment by jnrdt** [comment]
Hi,

The API have to consider a call made by the plugin, _eg_ PhantomJS : its user agent, the origin that is probably `localhost`....

You have to make in work in this particular conditions. If you can, take a look at the server side log.

**Comment by chenweihan** [comment]
Hi @jnrdt 
Yes，We found the reason.
When compiling， the prerender-spa-plugin use Hapi  to new start  Server   and cross-domain API request.

code:
.....
Server.start(function (error) {
          // If port is already bound, try again with another port
          if (error) return serveAndPrerenderRoute()

          var maxAttempts = options.maxAttempts || 5
          var attemptsSoFar = 0

          var phantomArguments = [
            Path.join(__dirname, 'phantom-page-render.js'),
            'http://localhost:' + port + route,  // http://localhost:8000
            JSON.stringify(options)
          ]
.....
